server:
  port: 8081

spring:
  data:
    cassandra:
      keyspace-name: capstone_inmemory_1
      local-datacenter: datacenter1
      contact-points: localhost
  jackson:
    serialization:
      INDENT_OUTPUT: true
  jmx:
    enabled: true

management:
  endpoint:
    httptrace:
      enabled: true

ignite:
  igniteInstanceName: clnt-instance-1
  clientMode: false
  peerClassLoadingEnabled: true
