version: '2'

services:

  app:
    build:
      context: ./demo-app
      args:
        JMX_REMOTE_PORT: 5005
    container_name: app
    depends_on:
      ignite-node-1:
        condition: service_started
    environment:
      - SERVER_PORT=8080
      - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
      - IGNITE_DISCOVERY_MULTICAST_ADDRESSES=ignite-node-1:47500
    ports:
      - "8080:8080"
      - "5005:5005"

  cassandra:
    image: "cassandra"
    container_name: cassandra
    expose:
      - "9042"
    ports:
      - "5007:5007"
    environment:
      - JAVA_TOOL_OPTIONSs=-Dcom.sun.management.jmxremote.ssl=false
          -Dcom.sun.management.jmxremote.authenticate=false
          -Dcom.sun.management.jmxremote.port=5007
          -Dcom.sun.management.jmxremote.rmi.port=5007
          -Dcom.sun.management.jmxremote.host=0.0.0.0
          -Djava.rmi.server.hostname=0.0.0.0
    volumes:
      - /tmp/cassandra-data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 10s
      timeout: 5s
      retries: 50

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./cassandra-data-loader/prepare-keyspace:/prepare-keyspace
    command: bash -c "echo loading cassandra keyspace && sleep 5 && /prepare-keyspace/load-data.sh"

  ignite-node-1:
      build:
        context: ./ignite-node
        args:
          JMX_REMOTE_PORT: 5001
      container_name: ignite-node-1
      depends_on:
        cassandra-load-keyspace:
          condition: service_started
      environment:
        - SERVER_PORT=8181
        - IGNITE_JETTY_PORT=8182
        - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
      ports:
        - "8181:8181"
        - "8182:8182"
        - "5001:5001"
      expose:
        - "10800" # thin client connections
        - "11211" # tcpPort
        - "47100" # TcpCommunicationSpi
        - "47500" # TcpDiscoverySp
        - "48100" # sharedMemoryPort
        - "49128" # Remote Management

  ignite-node-2:
    build:
      context: ./ignite-node
      args:
        JMX_REMOTE_PORT: 5002
    container_name: ignite-node-2
    depends_on:
      cassandra-load-keyspace:
        condition: service_started
    environment:
      - SERVER_PORT=8281
      - IGNITE_JETTY_PORT=8282
      - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
    ports:
      - "8281:8281"
      - "8282:8282"
      - "5002:5002"
    expose:
      - "10800" # thin client connections
      - "11211" # tcpPort
      - "47100" # TcpCommunicationSpi
      - "47500" # TcpDiscoverySp
      - "48100" # sharedMemoryPort
      - "49128" # Remote Management

  ignite-node-3:
    build:
      context: ./ignite-node
      args:
        JMX_REMOTE_PORT: 5003
    container_name: ignite-node-3
    depends_on:
      cassandra-load-keyspace:
        condition: service_started
    environment:
      - SERVER_PORT=8381
      - IGNITE_JETTY_PORT=8382
      - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
    ports:
      - "8381:8381"
      - "8382:8382"
      - "5003:5003"
    expose:
      - "10800" # thin client connections
      - "11211" # tcpPort
      - "47100" # TcpCommunicationSpi
      - "47500" # TcpDiscoverySp
      - "48100" # sharedMemoryPort
      - "49128" # Remote Management

